### PR TITLE
send multipart reply in case flow entry was empty

### PR DESCRIPTION
**Pull request by iHiroakiKawai**
Fixes the problem that switch does not send multipart
reply and keep silent when no flow entry was found.

### CODE REVIEW

**Comment by nickkaranatsios** [comment]
If we send back an empty flow stats reply we can only display the multipart-reply header to the user, which might not be enough information. Need to ask the opinion of other members. Please wait for the outcome.

**Comment by chibacchie** [comment]
Let me clarify desired multipart request/reply behavior. It would be great if someone could check if the following descriptions comply with the protocol specification and Trema Edge behaves as desired.
- Description
  A single struct ofp_desc object is always returned.
- Individual Flow Statistics
  An array of struct ofp_flow_stats is returned. The size of the array is zero if no matching flow entry found (i.e. multipart reply does not have body part).
- Aggregate Flow Statistics
  A single struct ofp_aggregate_stats_reply object is always returned.
- Table Statistics
  An array of struct ofp_table_stats is returned. The size of the array is equal to the number of flow tables. Thus the size must be 255 in case of Trema Switch.
- Table Features
  An array of struct ofp_table_features is returned. The size of the array must not be zero. If no matching table found, OFPET_BAD_REQUEST/OFPBRC_BAD_TABLE_ID is returned.
- Port Statistics
  An array of struct ofp_port_stats is returned. The size of the array is equal to or greater than zero. If no ports defined on a switch, the size of the array
  must be zero. If port_no in a request message is not OFPP_ANY and no matching port found, OFPET_BAD_REQUEST/OFPBRC_BAD_PORT is returned.
- Port Description
  An array of struct ofp_port is returned. The size of the array is equal to or greater than zero. If no ports defined on a switch, the size of the array
  must be zero.
- Queue Statistics
  An array of struct ofp_queue_stats is returned. The size of the array is equal to or greater than zero. If port_no and/or queue_id is specified in a request and
  no matching port/queue found, OFPET_QUEUE_OP_FAILED/OFPQOFC_BAD_PORT or OFPET_QUEUE_OP_FAILED/OFPQOFC_BAD_QUEUE is returned. If port_no and queue_id are not specified (i.e. OFPP_ANY and OFPQ_ALL are specified) and there is no configured queue, the size of the array must be zero. If queuing is not supported, OFPET_BAD_REQUEST/OFPBRC_BAD_MULTIPART is returned.
- Group Statistics
  An array of struct ofp_group_stats is returned. The size of the array is equal to or greater than zero. If group_id is specified in a request and no matching group found, the size of the array must be zero. If group_id is not specified (i.e. OFPG_ALL) and there is no group defined, the size of the array must be zero. If no any group is supported, OFPET_BAD_REQUEST/OFPBRC_BAD_MULTIPART is returned.
- Group Description
  An array of struct ofp_group_desc_stats is returned. The size of the array is zero if no group entry found. If no any group is supported, OFPET_BAD_REQUEST/OFPBRC_BAD_MULTIPART is returned.
- Group Features
  An array of struct ofp_group_features is returned. The size of the array is greater than zero. If no any group is supported, OFPET_BAD_REQUEST/OFPBRC_BAD_MULTIPART is returned.
- Meter Statistics
  An array of struct ofp_meter_stats is returned. The size of the array is equal to or greater than zero. If meter_id is specified in a request and no matching meter found, the size of the array must be zero. If meter_id is not specified (i.e. OFPM_ALL) and no meter defined, the size of the array must be zero. If metering function is not supported, OFPET_BAD_REQUEST/OFPBRC_BAD_MULTIPART is returned.
- Meter Configuration Statistics
  An array of struct ofp_meter_config is returned. The size of the array is equal to or greater than zero. If meter_id is specified in a request and no matching meter found, the size of the array is zero. If meter_id is not specified (i.e. OFPM_ALL) and no meter defined, the size of the array must be zero. If metering function is not supported, OFPET_BAD_REQUEST/OFPBRC_BAD_MULTIPART is returned.
- Meter Features Statistics
  A single struct ofp_meter_features object is returned. If metering function is not supported, OFPET_BAD_REQUEST/OFPBRC_BAD_MULTIPART is returned.

**Comment by iHiroakiKawai** [comment]
My patch is about Flow stats, and in that case, and the "body" is "an array of struct ofp_flow_stats" by specification. The message which the switch emits, has OFPMP_FLOW in ofp_multipart_reply type field. IMHO, it is very natural to transmit array of length 0.

**Comment by iHiroakiKawai** [comment]
I think we agree on SENDING multipart reply with empty body. The point is that without this patch, switch simply does not send multipart reply in case matching flow entry was empty.

**Comment by nickkaranatsios** [comment]
Fixed as above in https://github.com/trema/trema-edge/commit/eabfa969387264637f4b947061e2a28de986a672

**Pull request closed without merging**
